# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92981c398a575126dc6c2d94ced297e5bb27fa2a007faa75507b60d4cb80ec32f79ff1ae77af61774df757494f0d16e469d406ff7bc4bc151c56d5e425ebf6b1

test:
  secret_key_base: 506e5bb2ffbe7dcfe1973a274ff8da838bfb1ee80e3de3c92e567ca65ae1cc92ccb086a40973f35c9cffc3949bdb927eae1315706a77b35883f23fa53da64a3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
